const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Arr.Exps.Width
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{animQueue: 0},
	{posX: 0},
	{posY: 0},
	{value: 0},
	{isFill: 0},
	{energyLevelValue: 0},
	{orbitalTypeValue: 0},
	{valansCountValue: 0},
	{Tween: 0},
	{Flash: 0},
	{elementBox: 0},
	{falseBg: 0},
	{border: 0},
	{fullScreenBtn: 0},
	{shareBtn: 0},
	{audioBtn: 0},
	{refreshBtn: 0},
	{Fade: 0},
	{periodNames: 0},
	{dizilimBg: 0},
	{DragDrop: 0},
	{element: 0},
	{elementBorder: 0},
	{energyLevelBtn: 0},
	{valansCountBtn: 0},
	{orbitalTypeBtn: 0},
	{isActive: 0},
	{s: 0},
	{sd: 0},
	{sp: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{dizilimPrev: 0},
	{dizilimNext: 0},
	{dizilim: 0},
	{randomArray: 0},
	{AJAX: 0},
	{data: 0},
	{valansCountBtn2: 0},
	{orbitalTypeBtn2: 0},
	{energyLevelBtn2: 0},
	{Touch: 0},
	{Mouse: 0},
	{Browser: 0},
	{Audio: 0},
	{energyLevelBg: 0},
	{orbitalTypeBg: 0},
	{valansCountBg: 0},
	{Pin: 0},
	{hand: 0},
	{energyLevel: 0},
	{orbitalType: 0},
	{valansCount: 0},
	{animationQueue: 0},
	{soundControl: 0},
	{tutorialBtn: 0},
	{elementIndex: 0},
	{val: 0},
	{isTrue: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	elementBox: class extends self.ISpriteInstance {},
	falseBg: class extends self.ISpriteInstance {},
	border: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	periodNames: class extends self.ISpriteInstance {},
	dizilimBg: class extends self.ISpriteInstance {},
	element: class extends self.ISpriteInstance {},
	elementBorder: class extends self.ISpriteInstance {},
	energyLevelBtn: class extends self.ISpriteInstance {},
	valansCountBtn: class extends self.ISpriteInstance {},
	orbitalTypeBtn: class extends self.ISpriteInstance {},
	s: class extends self.ISpriteInstance {},
	sd: class extends self.ISpriteInstance {},
	sp: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	dizilimPrev: class extends self.ISpriteInstance {},
	dizilimNext: class extends self.ISpriteInstance {},
	dizilim: class extends self.ISpriteInstance {},
	randomArray: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	data: class extends self.IArrayInstance {},
	valansCountBtn2: class extends self.ISpriteInstance {},
	orbitalTypeBtn2: class extends self.ISpriteInstance {},
	energyLevelBtn2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	energyLevelBg: class extends self.ISpriteInstance {},
	orbitalTypeBg: class extends self.ISpriteInstance {},
	valansCountBg: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	energyLevel: class extends self.ISpriteInstance {},
	orbitalType: class extends self.ISpriteInstance {},
	valansCount: class extends self.ISpriteInstance {}
}